import React, { useState } from 'react';
import {
  X,
  Printer,
  Copy,
  Check,
  MapPin,
  Calendar,
  Clock,
  PhoneCall,
  Hotel,
} from 'lucide-react';
import { DayPlan, UserPreferences } from '../types/kerala';
import { formatDuration } from '../utils/geoRouting';

interface PrintSummaryModalProps {
  isOpen: boolean;
  onClose: () => void;
  dayPlans: DayPlan[];
  preferences: UserPreferences;
  totalKm: number;
  estimatedCost: number;
}

export const PrintSummaryModal: React.FC<PrintSummaryModalProps> = ({
  isOpen,
  onClose,
  dayPlans,
  preferences,
  totalKm,
  estimatedCost,
}) => {
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const handlePrint = () => {
    window.print();
  };

  const handleCopyText = () => {
    let summary = `🌴 KERALA DISCOVERY - TRIP ITINERARY 🌴\n`;
    summary += `Duration: ${preferences.days} Days | Pace: ${preferences.style.toUpperCase()}\n`;
    summary += `Travelers: ${preferences.travelers.length} (${preferences.travelers.map((t) => `${t.name}, age ${t.age}`).join(', ')})\n`;
    summary += `Total Road Distance: ${totalKm} km | Estimated Budget: ₹${estimatedCost.toLocaleString('en-IN')}\n\n`;

    dayPlans.forEach((dp) => {
      summary += `===============================\n`;
      summary += `DAY ${dp.day}: ${dp.title}\n`;
      summary += `Theme: ${dp.theme}\n`;
      summary += `Total Drive: ${formatDuration(dp.totalDriveMinutes)} (${dp.totalDistanceKm} km)\n`;
      summary += `Overnight Stay: ${dp.hotelSuggestion.name} (${dp.hotelSuggestion.area})\n\n`;

      dp.stops.forEach((stop, idx) => {
        summary += `  ${idx + 1}. ${stop.place.name} [${stop.place.district}]\n`;
        summary += `     Time: ${stop.scheduledStartTime} - ${stop.scheduledEndTime} (${formatDuration(stop.allocatedDuration)})\n`;
        summary += `     Highlights: ${stop.place.highlights.join(', ')}\n`;
        if (stop.travelTimeToNextMinutes > 0) {
          summary += `     🚗 Drive to next stop: ${formatDuration(stop.travelTimeToNextMinutes)} (${stop.travelDistanceToNextKm} km)\n`;
        }
        summary += `\n`;
      });
    });

    summary += `Emergency Contacts:\n`;
    summary += `- Kerala Tourism Police Helpline: 112\n`;
    summary += `- Highway Police Patrol: 9846 100 100\n`;
    summary += `- Childline Helpline: 1098\n`;

    navigator.clipboard.writeText(summary);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-6 bg-black/60 backdrop-blur-sm overflow-y-auto">
      <div className="bg-white rounded-3xl shadow-2xl border border-stone-200 w-full max-w-3xl overflow-hidden flex flex-col max-h-[92vh]">
        {/* Header */}
        <div className="bg-emerald-950 text-white px-6 py-4 flex items-center justify-between border-b border-emerald-800">
          <div className="flex items-center gap-2">
            <Printer className="w-5 h-5 text-emerald-400" />
            <h3 className="text-base font-bold font-serif">
              Export / Print Kerala Trip Plan
            </h3>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg hover:bg-emerald-900 text-emerald-300 hover:text-white transition"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Printable Document Area */}
        <div className="p-6 overflow-y-auto space-y-6 print:p-0">
          <div className="border-b border-stone-200 pb-4">
            <h2 className="text-xl font-extrabold text-stone-900 font-serif">
              Kerala Discovery Expedition Itinerary
            </h2>
            <p className="text-xs text-stone-500 mt-1">
              Custom curated itinerary generated by Kerala Discovery Travel Game engine
            </p>

            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mt-4 text-xs">
              <div className="bg-stone-50 p-2.5 rounded-xl border border-stone-200">
                <span className="text-stone-500 block text-[10px] uppercase font-bold">
                  Duration
                </span>
                <span className="font-bold text-stone-900">{preferences.days} Days</span>
              </div>
              <div className="bg-stone-50 p-2.5 rounded-xl border border-stone-200">
                <span className="text-stone-500 block text-[10px] uppercase font-bold">
                  Travelers
                </span>
                <span className="font-bold text-stone-900">
                  {preferences.travelers.length} Person(s)
                </span>
              </div>
              <div className="bg-stone-50 p-2.5 rounded-xl border border-stone-200">
                <span className="text-stone-500 block text-[10px] uppercase font-bold">
                  Total Road KMs
                </span>
                <span className="font-bold text-stone-900">{totalKm} km</span>
              </div>
              <div className="bg-stone-50 p-2.5 rounded-xl border border-stone-200">
                <span className="text-stone-500 block text-[10px] uppercase font-bold">
                  Est. Total Cost
                </span>
                <span className="font-bold text-emerald-700">
                  ₹{estimatedCost.toLocaleString('en-IN')}
                </span>
              </div>
            </div>
          </div>

          {/* Days breakdown */}
          <div className="space-y-6">
            {dayPlans.map((dp) => (
              <div
                key={dp.day}
                className="border border-stone-200 rounded-2xl p-4 bg-stone-50/50 space-y-3"
              >
                <div className="flex items-center justify-between border-b border-stone-200 pb-2">
                  <div>
                    <h3 className="text-sm font-bold text-stone-900">
                      Day {dp.day}: {dp.districtsVisited.join(' & ')}
                    </h3>
                    <div className="text-[11px] text-emerald-700 font-semibold">
                      {dp.theme}
                    </div>
                  </div>
                  <span className="text-xs text-stone-500 font-medium">
                    🚗 {formatDuration(dp.totalDriveMinutes)} · {dp.totalDistanceKm} km
                  </span>
                </div>

                <div className="space-y-2">
                  {dp.stops.map((stop, idx) => (
                    <div
                      key={stop.id}
                      className="bg-white p-3 rounded-xl border border-stone-200 text-xs flex items-start gap-3"
                    >
                      <span className="w-6 h-6 rounded-full bg-emerald-100 text-emerald-900 font-bold text-xs flex items-center justify-center shrink-0">
                        {idx + 1}
                      </span>
                      <div className="min-w-0 flex-1">
                        <div className="flex items-center justify-between">
                          <span className="font-bold text-stone-900">
                            {stop.place.name}
                          </span>
                          <span className="text-stone-500 font-mono text-[11px]">
                            {stop.scheduledStartTime} – {stop.scheduledEndTime}
                          </span>
                        </div>
                        <div className="text-[11px] text-stone-500 mt-0.5">
                          District: {stop.place.district} · Category:{' '}
                          {stop.place.category.join(', ')} · Hours:{' '}
                          {stop.place.opening_hours.open}–{stop.place.opening_hours.close}
                        </div>
                        {stop.travelTimeToNextMinutes > 0 && (
                          <div className="text-[10px] text-emerald-800 font-medium mt-1">
                            🚗 Next leg drive: {formatDuration(stop.travelTimeToNextMinutes)} (
                            {stop.travelDistanceToNextKm} km)
                          </div>
                        )}
                      </div>
                    </div>
                  ))}
                </div>

                <div className="p-2.5 bg-emerald-50 rounded-xl border border-emerald-200 text-xs flex items-center justify-between">
                  <span className="font-semibold text-emerald-950 flex items-center gap-1.5">
                    <Hotel className="w-3.5 h-3.5 text-emerald-700" />
                    Overnight Stay: {dp.hotelSuggestion.name}
                  </span>
                  <span className="text-stone-600 text-[11px]">
                    {dp.hotelSuggestion.area}
                  </span>
                </div>
              </div>
            ))}
          </div>

          {/* Emergency Contacts */}
          <div className="p-4 bg-stone-100 rounded-2xl border border-stone-200 text-xs space-y-1.5">
            <div className="font-bold text-stone-900 flex items-center gap-1.5">
              <PhoneCall className="w-3.5 h-3.5 text-emerald-700" />
              Essential Kerala Traveler Helplines:
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-2 text-[11px] text-stone-600 pt-1">
              <div>Police / Emergency: <span className="font-bold text-stone-900">112</span></div>
              <div>Highway Police: <span className="font-bold text-stone-900">9846 100 100</span></div>
              <div>Tourist Information: <span className="font-bold text-stone-900">1800 425 4747</span></div>
            </div>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="px-6 py-4 bg-stone-100 border-t border-stone-200 flex items-center justify-between print:hidden">
          <button
            onClick={handleCopyText}
            className="px-4 py-2 rounded-xl text-xs font-semibold bg-white border border-stone-300 text-stone-700 hover:bg-stone-50 transition flex items-center gap-1.5"
          >
            {copied ? <Check className="w-4 h-4 text-emerald-600" /> : <Copy className="w-4 h-4" />}
            <span>{copied ? 'Copied to Clipboard!' : 'Copy Text Itinerary'}</span>
          </button>

          <div className="flex items-center gap-2">
            <button
              onClick={onClose}
              className="px-4 py-2 rounded-xl text-xs font-semibold text-stone-600 hover:text-stone-800"
            >
              Close
            </button>
            <button
              onClick={handlePrint}
              className="px-5 py-2 rounded-xl text-xs font-bold bg-emerald-800 text-white hover:bg-emerald-900 transition flex items-center gap-1.5 shadow"
            >
              <Printer className="w-4 h-4" />
              Print Itinerary
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
